### ISSUE TITLE
Missing rtlights for Quake 1.5 E3M9 / E4M1-VALVE

### ISSUE THREAD

**Issue by mashakos** [hemebond/quake-rtlights#22]
Not an issue, more of a request for this secret level in the mod to get the rtlights treatment.
There is another map, E4M1-VALVE, which does not have rtlights to which I've made a copy of E4M1 rtlights with the -valve suffix and the maps seem to be identical in the first ten minutes.

**Comment by hemebond** [comment]
@mashakos I've uploaded some [rtlights for e3m9](https://raw.githubusercontent.com/hemebond/quake-rtlights/master/quake15/maps/e3m9.rtlights). I didn't even know that level existed :-D

As for `e4m1-valve`, it appears to be identical to `e4m1` unless something is wrong with my copy of the map. Do you see any actual differences between `e4m1` and `e4m1-valve`?

**Comment by mashakos** [comment]
awesome! I don't seem to see any differences between e4m1 and e4m1-valve but if I run into a unique area when playing I will reply with an update or perhaps open a new ticket if you prefer to close this one.
unrelated but, your work is so good with the maps you've tackled I am hoping you would be open to doing more. With other id tech 1 engine games perhaps. Hexen II comes to mind hehe! [https://youtu.be/HDITNYpWRUU](url)

**Comment by hemebond** [comment]
@mashakos I don't play any other id tech 1 games, but I do already have other on-going Quake 1-related projects (including a [texture pack](https://github.com/hemebond/quake-textures) that goes well with rtlights).

I'll close off this ticket but feel free to create others for any issues or additions.
